### ISSUE TITLE
Display OS version when scanning the network

### ISSUE THREAD

**Issue by rcvaram** [cvaram96/BNS-scanner#1]
Now this scanner only tells the ip address and the mac address. The OS version of the device is not shown. It is a feature for this scanner
More details about this scanner can be found in this [article](https://medium.com/@cvaram96/creating-own-network-scanner-using-python-f11a50a5ff77).

**Comment by erdepe-dad** [comment]
hello @cvaram96 , I made pull request for this issue. please review. thank you.

**Comment by rcvaram** [comment]
Sure
